### ISSUE TITLE
AttributeError: module 'pywhiten.cfg' has no attribute 'pkg_path'

### ISSUE THREAD

**Issue by SimonJMurphy** [erikstacey/pywhiten#1]
I'm trying to follow the tutorial, and my example.py looks like
```
import numpy as np
t,m = np.loadtxt("TIC120257786_lk.csv").T

import pywhiten
print(pywhiten.cfg.pkg_path)

pywhitener = pywhiten.PyWhitener(time=t, data=m)

pywhitener.auto()
```

When I run `python example.py`, I get this error:

> Traceback (most recent call last):
> 
>   File "/Users/sjm/Desktop/TESS_sandbox/pywhiten_tutorial/example.py", line 5, in <module>
> 
>     print(pywhiten.cfg.pkg_path)
> 
>           ^^^^^^^^^^^^^^^^^^^^^
> 
> AttributeError: module 'pywhiten.cfg' has no attribute 'pkg_path'

I'm running Python 3.11.5 on Mac OS 11.7.6

**Comment by erikstacey** [comment]
Sincere apologies for the slow response, unfortunately I was not automatically notified of the posting of this issue. This should be fixed by the updated [version 1.2](https://github.com/erikstacey/pywhiten/commit/87532dd70cf2825a9cd609d9e95f4b0984a89906) released in November. Cheers.
